import "@/styles/globals.css";
import "@/components/Navbar/navbar.css";
import "@/components/Header/header.css";
import "@/components/Footer/footer.css";
import "@/components/Button/button.css";
import "@/components/Section/HomeContent/content.css";
import "@/components/Section/HomeContent/recent.css";
import "@/components/Section/ProjectContent/projects.css";
import "@/components/Section/AboutContent/about.css";
import "@/components/Section/ContactContent/contact.css";
import Head from "next/head";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/router";
import LoadTransition from "@/components/loadTransition"; // Import the LoadTransition component

export default function App({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Ari Sandika | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AnimatePresence mode="wait">
        <motion.main
          className={`main selection:bg-dark selection:bg-opacity-70 selection:text-primary`}
          key={router.pathname}
        >
          <Navbar />
          <Component {...pageProps} />
          <Footer />
          <LoadTransition />
        </motion.main>
      </AnimatePresence>
    </>
  );
}
