import "@/styles/globals.css";
import "@/components/Navbar/navbar.css";
import "@/components/Hero/hero.css";
import "@/components/Footer/footer.css";
import "@/components/Button/button.css";
import "@/components/Section/HomeContent/content.css";
import "@/components/Section/ProjectContent/projects.css";
import "@/components/Section/AboutContent/about.css";
import "@/components/Section/ContactContent/contact.css";
import Head from "next/head";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Ari Sandika | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        className={`main selection:bg-dark selection:bg-opacity-70 selection:text-primary`}
      >
        <Navbar />
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  );
}
